(function () {

    'use strict';

    /**
     * external resources and requirements
     */
    var libs = {
        promotions: require('../promotions')
    };

    /**
     * Methods to be public through internals.exports
     * @type {Object}
     */
    var api = {

        /**
         * This guy returns the list of actions generated by each one of the
         * controllers inside the server
         *
         * @return {Array} Array of actions defined in each controller
         */
        getGETControllerActions: function() {
            return libs.promotions.getGETActions();
        },
        getPOSTControllerActions: function() {
            return libs.promotions.getPOSTActions();
        },
        getPUTControllerActions: function() {
            return libs.promotions.getPUTActions();
        },
        getDELControllerActions: function() {
            return libs.promotions.getDELActions();
        }
    };

    module.exports = api;

})();
